### ISSUE TITLE
Stretch: Qualifications and Certifications

### ISSUE THREAD

**Issue by Grantskie** [1086-Maria-Big-Data/JobAdAnalytics#22] opened 2021-08-26 13:46 UTC
What are the top three qualifications or certifications requested by Employers?

**Comment by vinceecws** [comment] 2021-09-06 16:05
Initial idea:
> Where the word **Qualification** is found on a job listing, the listed qualifications required for the position is likely to be in the next several lines. In HTML DOM, that would also be true.

Implementation:
Using the filtered index, iterate over all corresponding WARC records, then
a) Extract `<body>...</body>` of HTML payload using ArchiveSpark
b) Iterate over lines, finding the one that contains `[Qq]ualification[s]?`
c) Grab the next N lines & tokenize (also, convert all to lower-case)
d) Perform word count on all tokens

With the aggregated result, manually filter out all noise data (i.e. HTML tags, unrelated filler words etc.). If needed, drop all non-word characters to attempt to combine counts on same words that were formatted differently (i.e. bachelors' vs. bachelor's vs. bachelors)

**Comment by rustle003** [comment] 2021-09-07 15:22
The current, working implementation is in dire need of optimization. One suspicion is that, after processing the html body, the returned type is a collection of key-value pairs which is, in turn, flattened as a batch after all records are processed to then reduce the data set and obtain a word count. My experience with accumulators is limited but a potential solution to this proposed, yet unconfirmed, problem would be to bypass the reduction by accumulating on all qualifications key words. To give some perspective on the speed of the current implementation, one crawl has been running for 8 hours as of this moment.

**Comment by vinceecws** [comment] 2021-09-08 01:58
Upon a closer look into the Spark History Server, it was realized that the first official run on EMR was limited to a single vCore, and therefore was taking an impossibly long time. For context, the progress bar on YARN Application Server showed < 5% after ~19hrs.
<img width="700" alt="Screen Shot 2021-09-07 at 9 53 34 PM" src="https://user-images.githubusercontent.com/19466657/132433429-a489f03e-0678-4e37-8369-a241d3ffca76.png">

We therefore decided to terminate the job immediately and made the following changes to ensure partitions were honored by Spark.
https://github.com/1086-Maria-Big-Data/JobAdAnalytics/blob/518c8fdd4bee44908f0bf62f86407084f0d43c2f/src/main/scala/cc/queries/qualificationsCertifications.scala#L53-L63
Note the `.repartition()` calls on both the index DataFrame and the RDD[WarcRecords]. Both were set to 512 partitions as soon as possible after loading, to prevent any CPU-bound stages being limited to the original number of partitions. Only at the final `write()` stage, the partition was reduced to 1, for a single-file output.

**Comment by vinceecws** [comment] 2021-09-08 21:46
Subsequent jobs were orders faster, where a test run on a single crawl `CC-MAIN-2021-21` took ~27 minutes, and the full run on all crawls took 6 hours 42 minutes.
<img width="700" alt="Screen Shot 2021-09-08 at 5 35 02 PM" src="https://user-images.githubusercontent.com/19466657/132588772-89cd6e0d-bd71-40b7-90ec-bb8b79561c45.png">

Additionally, we also ran an identically structured query, but this time for the `certifications` criteria instead. This time, it took 10 hours 50 minutes over all crawls.
<img width="700" alt="Screen Shot 2021-09-08 at 5 40 07 PM" src="https://user-images.githubusercontent.com/19466657/132589332-11d518bf-757b-4e0c-a46e-13f275537841.png">

Upon closer observation on the YARN ResourceManager UI, it was found that all submitted jobs on the cluster were only assigned a maximum of 16 vCores and ~23GB of memory. This is due to an oversight concerning the YARN Scheduler configuration. The CapacityScheduler by default places an upper bound and lower bound on the resources assigned to any job. In this case, a better choice would be the FairScheduler, which will allocate all resources to the job, if there is only one running on the cluster.
<img width="700" alt="Screen Shot 2021-09-08 at 5 41 20 PM" src="https://user-images.githubusercontent.com/19466657/132589465-b7c100b7-2ec8-4523-bb32-d032472244b1.png">

> Summary:
1) `.repartition()` to a proper figure allowed full use of available resources, speeding up jobs significantly.
2) YARN CapacityScheduler causes underutilization of the cluster and limits any job to only 1/4 of the available resources, even if it's the only job running. A better choice would be the FairScheduler.

**Comment by vinceecws** [comment] 2021-09-08 21:51
For this query, we had 2 main findings:

1) The proportion of education-level requirements for tech-job postings:
<img width="700" alt="Sheet_2-2" src="https://user-images.githubusercontent.com/19466657/132590230-02048d7b-566e-42b8-9400-de08056f9cef.png">

2) The proportion of certification types for tech-job postings:
> Emphasis on the significance of demand for ScrumMaster certifications (denoted "sm").
<img width="700" alt="Sheet_1" src="https://user-images.githubusercontent.com/19466657/132590350-c328280a-08a5-4e5f-b963-6321ffe32831.png">

**Closed by vinceecws** 2021-09-08 21:51 UTC
Labels: enhancement, backlog
